// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="image_filter,hls_ip_2017_4,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xc7z020clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=8.750000,HLS_SYN_LAT=-1,HLS_SYN_TPT=-1,HLS_SYN_MEM=23,HLS_SYN_DSP=65,HLS_SYN_FF=9806,HLS_SYN_LUT=17971}" *)

module image_filter (
        s_axi_CONTROL_BUS_AWVALID,
        s_axi_CONTROL_BUS_AWREADY,
        s_axi_CONTROL_BUS_AWADDR,
        s_axi_CONTROL_BUS_WVALID,
        s_axi_CONTROL_BUS_WREADY,
        s_axi_CONTROL_BUS_WDATA,
        s_axi_CONTROL_BUS_WSTRB,
        s_axi_CONTROL_BUS_ARVALID,
        s_axi_CONTROL_BUS_ARREADY,
        s_axi_CONTROL_BUS_ARADDR,
        s_axi_CONTROL_BUS_RVALID,
        s_axi_CONTROL_BUS_RREADY,
        s_axi_CONTROL_BUS_RDATA,
        s_axi_CONTROL_BUS_RRESP,
        s_axi_CONTROL_BUS_BVALID,
        s_axi_CONTROL_BUS_BREADY,
        s_axi_CONTROL_BUS_BRESP,
        ap_clk,
        ap_rst_n,
        interrupt,
        m_axi_hostmem_1_AWVALID,
        m_axi_hostmem_1_AWREADY,
        m_axi_hostmem_1_AWADDR,
        m_axi_hostmem_1_AWID,
        m_axi_hostmem_1_AWLEN,
        m_axi_hostmem_1_AWSIZE,
        m_axi_hostmem_1_AWBURST,
        m_axi_hostmem_1_AWLOCK,
        m_axi_hostmem_1_AWCACHE,
        m_axi_hostmem_1_AWPROT,
        m_axi_hostmem_1_AWQOS,
        m_axi_hostmem_1_AWREGION,
        m_axi_hostmem_1_AWUSER,
        m_axi_hostmem_1_WVALID,
        m_axi_hostmem_1_WREADY,
        m_axi_hostmem_1_WDATA,
        m_axi_hostmem_1_WSTRB,
        m_axi_hostmem_1_WLAST,
        m_axi_hostmem_1_WID,
        m_axi_hostmem_1_WUSER,
        m_axi_hostmem_1_ARVALID,
        m_axi_hostmem_1_ARREADY,
        m_axi_hostmem_1_ARADDR,
        m_axi_hostmem_1_ARID,
        m_axi_hostmem_1_ARLEN,
        m_axi_hostmem_1_ARSIZE,
        m_axi_hostmem_1_ARBURST,
        m_axi_hostmem_1_ARLOCK,
        m_axi_hostmem_1_ARCACHE,
        m_axi_hostmem_1_ARPROT,
        m_axi_hostmem_1_ARQOS,
        m_axi_hostmem_1_ARREGION,
        m_axi_hostmem_1_ARUSER,
        m_axi_hostmem_1_RVALID,
        m_axi_hostmem_1_RREADY,
        m_axi_hostmem_1_RDATA,
        m_axi_hostmem_1_RLAST,
        m_axi_hostmem_1_RID,
        m_axi_hostmem_1_RUSER,
        m_axi_hostmem_1_RRESP,
        m_axi_hostmem_1_BVALID,
        m_axi_hostmem_1_BREADY,
        m_axi_hostmem_1_BRESP,
        m_axi_hostmem_1_BID,
        m_axi_hostmem_1_BUSER,
        m_axi_hostmem_2_AWVALID,
        m_axi_hostmem_2_AWREADY,
        m_axi_hostmem_2_AWADDR,
        m_axi_hostmem_2_AWID,
        m_axi_hostmem_2_AWLEN,
        m_axi_hostmem_2_AWSIZE,
        m_axi_hostmem_2_AWBURST,
        m_axi_hostmem_2_AWLOCK,
        m_axi_hostmem_2_AWCACHE,
        m_axi_hostmem_2_AWPROT,
        m_axi_hostmem_2_AWQOS,
        m_axi_hostmem_2_AWREGION,
        m_axi_hostmem_2_AWUSER,
        m_axi_hostmem_2_WVALID,
        m_axi_hostmem_2_WREADY,
        m_axi_hostmem_2_WDATA,
        m_axi_hostmem_2_WSTRB,
        m_axi_hostmem_2_WLAST,
        m_axi_hostmem_2_WID,
        m_axi_hostmem_2_WUSER,
        m_axi_hostmem_2_ARVALID,
        m_axi_hostmem_2_ARREADY,
        m_axi_hostmem_2_ARADDR,
        m_axi_hostmem_2_ARID,
        m_axi_hostmem_2_ARLEN,
        m_axi_hostmem_2_ARSIZE,
        m_axi_hostmem_2_ARBURST,
        m_axi_hostmem_2_ARLOCK,
        m_axi_hostmem_2_ARCACHE,
        m_axi_hostmem_2_ARPROT,
        m_axi_hostmem_2_ARQOS,
        m_axi_hostmem_2_ARREGION,
        m_axi_hostmem_2_ARUSER,
        m_axi_hostmem_2_RVALID,
        m_axi_hostmem_2_RREADY,
        m_axi_hostmem_2_RDATA,
        m_axi_hostmem_2_RLAST,
        m_axi_hostmem_2_RID,
        m_axi_hostmem_2_RUSER,
        m_axi_hostmem_2_RRESP,
        m_axi_hostmem_2_BVALID,
        m_axi_hostmem_2_BREADY,
        m_axi_hostmem_2_BRESP,
        m_axi_hostmem_2_BID,
        m_axi_hostmem_2_BUSER
);

parameter    C_S_AXI_CONTROL_BUS_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_BUS_ADDR_WIDTH = 6;
parameter    C_S_AXI_DATA_WIDTH = 32;
parameter    C_S_AXI_ADDR_WIDTH = 32;
parameter    C_M_AXI_HOSTMEM_1_ID_WIDTH = 1;
parameter    C_M_AXI_HOSTMEM_1_ADDR_WIDTH = 32;
parameter    C_M_AXI_HOSTMEM_1_DATA_WIDTH = 32;
parameter    C_M_AXI_HOSTMEM_1_AWUSER_WIDTH = 1;
parameter    C_M_AXI_HOSTMEM_1_ARUSER_WIDTH = 1;
parameter    C_M_AXI_HOSTMEM_1_WUSER_WIDTH = 1;
parameter    C_M_AXI_HOSTMEM_1_RUSER_WIDTH = 1;
parameter    C_M_AXI_HOSTMEM_1_BUSER_WIDTH = 1;
parameter    C_M_AXI_HOSTMEM_1_USER_VALUE = 0;
parameter    C_M_AXI_HOSTMEM_1_PROT_VALUE = 0;
parameter    C_M_AXI_HOSTMEM_1_CACHE_VALUE = 3;
parameter    C_M_AXI_ID_WIDTH = 1;
parameter    C_M_AXI_ADDR_WIDTH = 32;
parameter    C_M_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_AWUSER_WIDTH = 1;
parameter    C_M_AXI_ARUSER_WIDTH = 1;
parameter    C_M_AXI_WUSER_WIDTH = 1;
parameter    C_M_AXI_RUSER_WIDTH = 1;
parameter    C_M_AXI_BUSER_WIDTH = 1;
parameter    C_M_AXI_HOSTMEM_2_ID_WIDTH = 1;
parameter    C_M_AXI_HOSTMEM_2_ADDR_WIDTH = 32;
parameter    C_M_AXI_HOSTMEM_2_DATA_WIDTH = 32;
parameter    C_M_AXI_HOSTMEM_2_AWUSER_WIDTH = 1;
parameter    C_M_AXI_HOSTMEM_2_ARUSER_WIDTH = 1;
parameter    C_M_AXI_HOSTMEM_2_WUSER_WIDTH = 1;
parameter    C_M_AXI_HOSTMEM_2_RUSER_WIDTH = 1;
parameter    C_M_AXI_HOSTMEM_2_BUSER_WIDTH = 1;
parameter    C_M_AXI_HOSTMEM_2_USER_VALUE = 0;
parameter    C_M_AXI_HOSTMEM_2_PROT_VALUE = 0;
parameter    C_M_AXI_HOSTMEM_2_CACHE_VALUE = 3;

parameter C_S_AXI_CONTROL_BUS_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_HOSTMEM_1_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_HOSTMEM_2_WSTRB_WIDTH = (32 / 8);

input   s_axi_CONTROL_BUS_AWVALID;
output   s_axi_CONTROL_BUS_AWREADY;
input  [C_S_AXI_CONTROL_BUS_ADDR_WIDTH - 1:0] s_axi_CONTROL_BUS_AWADDR;
input   s_axi_CONTROL_BUS_WVALID;
output   s_axi_CONTROL_BUS_WREADY;
input  [C_S_AXI_CONTROL_BUS_DATA_WIDTH - 1:0] s_axi_CONTROL_BUS_WDATA;
input  [C_S_AXI_CONTROL_BUS_WSTRB_WIDTH - 1:0] s_axi_CONTROL_BUS_WSTRB;
input   s_axi_CONTROL_BUS_ARVALID;
output   s_axi_CONTROL_BUS_ARREADY;
input  [C_S_AXI_CONTROL_BUS_ADDR_WIDTH - 1:0] s_axi_CONTROL_BUS_ARADDR;
output   s_axi_CONTROL_BUS_RVALID;
input   s_axi_CONTROL_BUS_RREADY;
output  [C_S_AXI_CONTROL_BUS_DATA_WIDTH - 1:0] s_axi_CONTROL_BUS_RDATA;
output  [1:0] s_axi_CONTROL_BUS_RRESP;
output   s_axi_CONTROL_BUS_BVALID;
input   s_axi_CONTROL_BUS_BREADY;
output  [1:0] s_axi_CONTROL_BUS_BRESP;
input   ap_clk;
input   ap_rst_n;
output   interrupt;
output   m_axi_hostmem_1_AWVALID;
input   m_axi_hostmem_1_AWREADY;
output  [C_M_AXI_HOSTMEM_1_ADDR_WIDTH - 1:0] m_axi_hostmem_1_AWADDR;
output  [C_M_AXI_HOSTMEM_1_ID_WIDTH - 1:0] m_axi_hostmem_1_AWID;
output  [7:0] m_axi_hostmem_1_AWLEN;
output  [2:0] m_axi_hostmem_1_AWSIZE;
output  [1:0] m_axi_hostmem_1_AWBURST;
output  [1:0] m_axi_hostmem_1_AWLOCK;
output  [3:0] m_axi_hostmem_1_AWCACHE;
output  [2:0] m_axi_hostmem_1_AWPROT;
output  [3:0] m_axi_hostmem_1_AWQOS;
output  [3:0] m_axi_hostmem_1_AWREGION;
output  [C_M_AXI_HOSTMEM_1_AWUSER_WIDTH - 1:0] m_axi_hostmem_1_AWUSER;
output   m_axi_hostmem_1_WVALID;
input   m_axi_hostmem_1_WREADY;
output  [C_M_AXI_HOSTMEM_1_DATA_WIDTH - 1:0] m_axi_hostmem_1_WDATA;
output  [C_M_AXI_HOSTMEM_1_WSTRB_WIDTH - 1:0] m_axi_hostmem_1_WSTRB;
output   m_axi_hostmem_1_WLAST;
output  [C_M_AXI_HOSTMEM_1_ID_WIDTH - 1:0] m_axi_hostmem_1_WID;
output  [C_M_AXI_HOSTMEM_1_WUSER_WIDTH - 1:0] m_axi_hostmem_1_WUSER;
output   m_axi_hostmem_1_ARVALID;
input   m_axi_hostmem_1_ARREADY;
output  [C_M_AXI_HOSTMEM_1_ADDR_WIDTH - 1:0] m_axi_hostmem_1_ARADDR;
output  [C_M_AXI_HOSTMEM_1_ID_WIDTH - 1:0] m_axi_hostmem_1_ARID;
output  [7:0] m_axi_hostmem_1_ARLEN;
output  [2:0] m_axi_hostmem_1_ARSIZE;
output  [1:0] m_axi_hostmem_1_ARBURST;
output  [1:0] m_axi_hostmem_1_ARLOCK;
output  [3:0] m_axi_hostmem_1_ARCACHE;
output  [2:0] m_axi_hostmem_1_ARPROT;
output  [3:0] m_axi_hostmem_1_ARQOS;
output  [3:0] m_axi_hostmem_1_ARREGION;
output  [C_M_AXI_HOSTMEM_1_ARUSER_WIDTH - 1:0] m_axi_hostmem_1_ARUSER;
input   m_axi_hostmem_1_RVALID;
output   m_axi_hostmem_1_RREADY;
input  [C_M_AXI_HOSTMEM_1_DATA_WIDTH - 1:0] m_axi_hostmem_1_RDATA;
input   m_axi_hostmem_1_RLAST;
input  [C_M_AXI_HOSTMEM_1_ID_WIDTH - 1:0] m_axi_hostmem_1_RID;
input  [C_M_AXI_HOSTMEM_1_RUSER_WIDTH - 1:0] m_axi_hostmem_1_RUSER;
input  [1:0] m_axi_hostmem_1_RRESP;
input   m_axi_hostmem_1_BVALID;
output   m_axi_hostmem_1_BREADY;
input  [1:0] m_axi_hostmem_1_BRESP;
input  [C_M_AXI_HOSTMEM_1_ID_WIDTH - 1:0] m_axi_hostmem_1_BID;
input  [C_M_AXI_HOSTMEM_1_BUSER_WIDTH - 1:0] m_axi_hostmem_1_BUSER;
output   m_axi_hostmem_2_AWVALID;
input   m_axi_hostmem_2_AWREADY;
output  [C_M_AXI_HOSTMEM_2_ADDR_WIDTH - 1:0] m_axi_hostmem_2_AWADDR;
output  [C_M_AXI_HOSTMEM_2_ID_WIDTH - 1:0] m_axi_hostmem_2_AWID;
output  [7:0] m_axi_hostmem_2_AWLEN;
output  [2:0] m_axi_hostmem_2_AWSIZE;
output  [1:0] m_axi_hostmem_2_AWBURST;
output  [1:0] m_axi_hostmem_2_AWLOCK;
output  [3:0] m_axi_hostmem_2_AWCACHE;
output  [2:0] m_axi_hostmem_2_AWPROT;
output  [3:0] m_axi_hostmem_2_AWQOS;
output  [3:0] m_axi_hostmem_2_AWREGION;
output  [C_M_AXI_HOSTMEM_2_AWUSER_WIDTH - 1:0] m_axi_hostmem_2_AWUSER;
output   m_axi_hostmem_2_WVALID;
input   m_axi_hostmem_2_WREADY;
output  [C_M_AXI_HOSTMEM_2_DATA_WIDTH - 1:0] m_axi_hostmem_2_WDATA;
output  [C_M_AXI_HOSTMEM_2_WSTRB_WIDTH - 1:0] m_axi_hostmem_2_WSTRB;
output   m_axi_hostmem_2_WLAST;
output  [C_M_AXI_HOSTMEM_2_ID_WIDTH - 1:0] m_axi_hostmem_2_WID;
output  [C_M_AXI_HOSTMEM_2_WUSER_WIDTH - 1:0] m_axi_hostmem_2_WUSER;
output   m_axi_hostmem_2_ARVALID;
input   m_axi_hostmem_2_ARREADY;
output  [C_M_AXI_HOSTMEM_2_ADDR_WIDTH - 1:0] m_axi_hostmem_2_ARADDR;
output  [C_M_AXI_HOSTMEM_2_ID_WIDTH - 1:0] m_axi_hostmem_2_ARID;
output  [7:0] m_axi_hostmem_2_ARLEN;
output  [2:0] m_axi_hostmem_2_ARSIZE;
output  [1:0] m_axi_hostmem_2_ARBURST;
output  [1:0] m_axi_hostmem_2_ARLOCK;
output  [3:0] m_axi_hostmem_2_ARCACHE;
output  [2:0] m_axi_hostmem_2_ARPROT;
output  [3:0] m_axi_hostmem_2_ARQOS;
output  [3:0] m_axi_hostmem_2_ARREGION;
output  [C_M_AXI_HOSTMEM_2_ARUSER_WIDTH - 1:0] m_axi_hostmem_2_ARUSER;
input   m_axi_hostmem_2_RVALID;
output   m_axi_hostmem_2_RREADY;
input  [C_M_AXI_HOSTMEM_2_DATA_WIDTH - 1:0] m_axi_hostmem_2_RDATA;
input   m_axi_hostmem_2_RLAST;
input  [C_M_AXI_HOSTMEM_2_ID_WIDTH - 1:0] m_axi_hostmem_2_RID;
input  [C_M_AXI_HOSTMEM_2_RUSER_WIDTH - 1:0] m_axi_hostmem_2_RUSER;
input  [1:0] m_axi_hostmem_2_RRESP;
input   m_axi_hostmem_2_BVALID;
output   m_axi_hostmem_2_BREADY;
input  [1:0] m_axi_hostmem_2_BRESP;
input  [C_M_AXI_HOSTMEM_2_ID_WIDTH - 1:0] m_axi_hostmem_2_BID;
input  [C_M_AXI_HOSTMEM_2_BUSER_WIDTH - 1:0] m_axi_hostmem_2_BUSER;

reg    ap_rst_n_inv;
wire    ap_start;
wire    ap_ready;
wire    ap_done;
wire    ap_idle;
wire   [31:0] in_V;
wire   [31:0] out_V;
wire   [31:0] rows;
wire   [31:0] cols;
wire    hostmem_1_AWREADY;
wire    hostmem_1_WREADY;
wire    hostmem_1_ARREADY;
wire    hostmem_1_RVALID;
wire   [31:0] hostmem_1_RDATA;
wire    hostmem_1_RLAST;
wire   [0:0] hostmem_1_RID;
wire   [0:0] hostmem_1_RUSER;
wire   [1:0] hostmem_1_RRESP;
wire    hostmem_1_BVALID;
wire   [1:0] hostmem_1_BRESP;
wire   [0:0] hostmem_1_BID;
wire   [0:0] hostmem_1_BUSER;
wire    hostmem_2_AWREADY;
wire    hostmem_2_WREADY;
wire    hostmem_2_ARREADY;
wire    hostmem_2_RVALID;
wire   [31:0] hostmem_2_RDATA;
wire    hostmem_2_RLAST;
wire   [0:0] hostmem_2_RID;
wire   [0:0] hostmem_2_RUSER;
wire   [1:0] hostmem_2_RRESP;
wire    hostmem_2_BVALID;
wire   [1:0] hostmem_2_BRESP;
wire   [0:0] hostmem_2_BID;
wire   [0:0] hostmem_2_BUSER;
wire    Mem2Stream_Batch9_U0_ap_start;
wire    Mem2Stream_Batch9_U0_start_full_n;
wire    Mem2Stream_Batch9_U0_ap_done;
wire    Mem2Stream_Batch9_U0_ap_continue;
wire    Mem2Stream_Batch9_U0_ap_idle;
wire    Mem2Stream_Batch9_U0_ap_ready;
wire    Mem2Stream_Batch9_U0_start_out;
wire    Mem2Stream_Batch9_U0_start_write;
wire    Mem2Stream_Batch9_U0_m_axi_in_V_AWVALID;
wire   [31:0] Mem2Stream_Batch9_U0_m_axi_in_V_AWADDR;
wire   [0:0] Mem2Stream_Batch9_U0_m_axi_in_V_AWID;
wire   [31:0] Mem2Stream_Batch9_U0_m_axi_in_V_AWLEN;
wire   [2:0] Mem2Stream_Batch9_U0_m_axi_in_V_AWSIZE;
wire   [1:0] Mem2Stream_Batch9_U0_m_axi_in_V_AWBURST;
wire   [1:0] Mem2Stream_Batch9_U0_m_axi_in_V_AWLOCK;
wire   [3:0] Mem2Stream_Batch9_U0_m_axi_in_V_AWCACHE;
wire   [2:0] Mem2Stream_Batch9_U0_m_axi_in_V_AWPROT;
wire   [3:0] Mem2Stream_Batch9_U0_m_axi_in_V_AWQOS;
wire   [3:0] Mem2Stream_Batch9_U0_m_axi_in_V_AWREGION;
wire   [0:0] Mem2Stream_Batch9_U0_m_axi_in_V_AWUSER;
wire    Mem2Stream_Batch9_U0_m_axi_in_V_WVALID;
wire   [31:0] Mem2Stream_Batch9_U0_m_axi_in_V_WDATA;
wire   [3:0] Mem2Stream_Batch9_U0_m_axi_in_V_WSTRB;
wire    Mem2Stream_Batch9_U0_m_axi_in_V_WLAST;
wire   [0:0] Mem2Stream_Batch9_U0_m_axi_in_V_WID;
wire   [0:0] Mem2Stream_Batch9_U0_m_axi_in_V_WUSER;
wire    Mem2Stream_Batch9_U0_m_axi_in_V_ARVALID;
wire   [31:0] Mem2Stream_Batch9_U0_m_axi_in_V_ARADDR;
wire   [0:0] Mem2Stream_Batch9_U0_m_axi_in_V_ARID;
wire   [31:0] Mem2Stream_Batch9_U0_m_axi_in_V_ARLEN;
wire   [2:0] Mem2Stream_Batch9_U0_m_axi_in_V_ARSIZE;
wire   [1:0] Mem2Stream_Batch9_U0_m_axi_in_V_ARBURST;
wire   [1:0] Mem2Stream_Batch9_U0_m_axi_in_V_ARLOCK;
wire   [3:0] Mem2Stream_Batch9_U0_m_axi_in_V_ARCACHE;
wire   [2:0] Mem2Stream_Batch9_U0_m_axi_in_V_ARPROT;
wire   [3:0] Mem2Stream_Batch9_U0_m_axi_in_V_ARQOS;
wire   [3:0] Mem2Stream_Batch9_U0_m_axi_in_V_ARREGION;
wire   [0:0] Mem2Stream_Batch9_U0_m_axi_in_V_ARUSER;
wire    Mem2Stream_Batch9_U0_m_axi_in_V_RREADY;
wire    Mem2Stream_Batch9_U0_m_axi_in_V_BREADY;
wire   [31:0] Mem2Stream_Batch9_U0_out_V_V_din;
wire    Mem2Stream_Batch9_U0_out_V_V_write;
wire   [31:0] Mem2Stream_Batch9_U0_out_V_out_din;
wire    Mem2Stream_Batch9_U0_out_V_out_write;
wire    bgr2gray_U0_ap_start;
wire    bgr2gray_U0_ap_done;
wire    bgr2gray_U0_ap_continue;
wire    bgr2gray_U0_ap_idle;
wire    bgr2gray_U0_ap_ready;
wire    bgr2gray_U0_start_out;
wire    bgr2gray_U0_start_write;
wire    bgr2gray_U0_src_V_V_read;
wire   [7:0] bgr2gray_U0_dst_V_V_din;
wire    bgr2gray_U0_dst_V_V_write;
wire    gaussianBlur_U0_ap_start;
wire    gaussianBlur_U0_start_full_n;
wire    gaussianBlur_U0_ap_done;
wire    gaussianBlur_U0_ap_continue;
wire    gaussianBlur_U0_ap_idle;
wire    gaussianBlur_U0_ap_ready;
wire    gaussianBlur_U0_start_out;
wire    gaussianBlur_U0_start_write;
wire    gaussianBlur_U0_src_V_V_read;
wire   [7:0] gaussianBlur_U0_dst_x_V_V_din;
wire    gaussianBlur_U0_dst_x_V_V_write;
wire   [7:0] gaussianBlur_U0_dst_y_V_V_din;
wire    gaussianBlur_U0_dst_y_V_V_write;
wire    sobel_x_U0_ap_start;
wire    sobel_x_U0_ap_done;
wire    sobel_x_U0_ap_continue;
wire    sobel_x_U0_ap_idle;
wire    sobel_x_U0_ap_ready;
wire    sobel_x_U0_start_out;
wire    sobel_x_U0_start_write;
wire    sobel_x_U0_src_V_V_read;
wire   [7:0] sobel_x_U0_dst_V_V_din;
wire    sobel_x_U0_dst_V_V_write;
wire    sobel_y_U0_ap_start;
wire    sobel_y_U0_ap_done;
wire    sobel_y_U0_ap_continue;
wire    sobel_y_U0_ap_idle;
wire    sobel_y_U0_ap_ready;
wire    sobel_y_U0_src_V_V_read;
wire   [7:0] sobel_y_U0_dst_V_V_din;
wire    sobel_y_U0_dst_V_V_write;
wire    addWeighted_U0_ap_start;
wire    addWeighted_U0_ap_done;
wire    addWeighted_U0_ap_continue;
wire    addWeighted_U0_ap_idle;
wire    addWeighted_U0_ap_ready;
wire    addWeighted_U0_start_out;
wire    addWeighted_U0_start_write;
wire    addWeighted_U0_src_x_V_V_read;
wire    addWeighted_U0_src_y_V_V_read;
wire   [7:0] addWeighted_U0_dst_V_V_din;
wire    addWeighted_U0_dst_V_V_write;
wire    gray2bgr_U0_ap_start;
wire    gray2bgr_U0_ap_done;
wire    gray2bgr_U0_ap_continue;
wire    gray2bgr_U0_ap_idle;
wire    gray2bgr_U0_ap_ready;
wire    gray2bgr_U0_src_V_V_read;
wire   [31:0] gray2bgr_U0_dst_V_V_din;
wire    gray2bgr_U0_dst_V_V_write;
wire    Stream2Mem_Batch_U0_ap_start;
wire    Stream2Mem_Batch_U0_ap_done;
wire    Stream2Mem_Batch_U0_ap_continue;
wire    Stream2Mem_Batch_U0_ap_idle;
wire    Stream2Mem_Batch_U0_ap_ready;
wire    Stream2Mem_Batch_U0_in_V_V_read;
wire    Stream2Mem_Batch_U0_m_axi_out_V_AWVALID;
wire   [31:0] Stream2Mem_Batch_U0_m_axi_out_V_AWADDR;
wire   [0:0] Stream2Mem_Batch_U0_m_axi_out_V_AWID;
wire   [31:0] Stream2Mem_Batch_U0_m_axi_out_V_AWLEN;
wire   [2:0] Stream2Mem_Batch_U0_m_axi_out_V_AWSIZE;
wire   [1:0] Stream2Mem_Batch_U0_m_axi_out_V_AWBURST;
wire   [1:0] Stream2Mem_Batch_U0_m_axi_out_V_AWLOCK;
wire   [3:0] Stream2Mem_Batch_U0_m_axi_out_V_AWCACHE;
wire   [2:0] Stream2Mem_Batch_U0_m_axi_out_V_AWPROT;
wire   [3:0] Stream2Mem_Batch_U0_m_axi_out_V_AWQOS;
wire   [3:0] Stream2Mem_Batch_U0_m_axi_out_V_AWREGION;
wire   [0:0] Stream2Mem_Batch_U0_m_axi_out_V_AWUSER;
wire    Stream2Mem_Batch_U0_m_axi_out_V_WVALID;
wire   [31:0] Stream2Mem_Batch_U0_m_axi_out_V_WDATA;
wire   [3:0] Stream2Mem_Batch_U0_m_axi_out_V_WSTRB;
wire    Stream2Mem_Batch_U0_m_axi_out_V_WLAST;
wire   [0:0] Stream2Mem_Batch_U0_m_axi_out_V_WID;
wire   [0:0] Stream2Mem_Batch_U0_m_axi_out_V_WUSER;
wire    Stream2Mem_Batch_U0_m_axi_out_V_ARVALID;
wire   [31:0] Stream2Mem_Batch_U0_m_axi_out_V_ARADDR;
wire   [0:0] Stream2Mem_Batch_U0_m_axi_out_V_ARID;
wire   [31:0] Stream2Mem_Batch_U0_m_axi_out_V_ARLEN;
wire   [2:0] Stream2Mem_Batch_U0_m_axi_out_V_ARSIZE;
wire   [1:0] Stream2Mem_Batch_U0_m_axi_out_V_ARBURST;
wire   [1:0] Stream2Mem_Batch_U0_m_axi_out_V_ARLOCK;
wire   [3:0] Stream2Mem_Batch_U0_m_axi_out_V_ARCACHE;
wire   [2:0] Stream2Mem_Batch_U0_m_axi_out_V_ARPROT;
wire   [3:0] Stream2Mem_Batch_U0_m_axi_out_V_ARQOS;
wire   [3:0] Stream2Mem_Batch_U0_m_axi_out_V_ARREGION;
wire   [0:0] Stream2Mem_Batch_U0_m_axi_out_V_ARUSER;
wire    Stream2Mem_Batch_U0_m_axi_out_V_RREADY;
wire    Stream2Mem_Batch_U0_m_axi_out_V_BREADY;
wire    Stream2Mem_Batch_U0_out_V_offset_read;
wire    ap_sync_continue;
wire    in_stream_V_V_full_n;
wire   [31:0] in_stream_V_V_dout;
wire    in_stream_V_V_empty_n;
wire    out_V_c_full_n;
wire   [31:0] out_V_c_dout;
wire    out_V_c_empty_n;
wire    gray_stream_V_V_full_n;
wire   [7:0] gray_stream_V_V_dout;
wire    gray_stream_V_V_empty_n;
wire    gaussian_stream_x_V_s_full_n;
wire   [7:0] gaussian_stream_x_V_s_dout;
wire    gaussian_stream_x_V_s_empty_n;
wire    gaussian_stream_y_V_s_full_n;
wire   [7:0] gaussian_stream_y_V_s_dout;
wire    gaussian_stream_y_V_s_empty_n;
wire    sobel_stream_x_V_V_full_n;
wire   [7:0] sobel_stream_x_V_V_dout;
wire    sobel_stream_x_V_V_empty_n;
wire    sobel_stream_y_V_V_full_n;
wire   [7:0] sobel_stream_y_V_V_dout;
wire    sobel_stream_y_V_V_empty_n;
wire    addWeight_stream_V_V_full_n;
wire   [7:0] addWeight_stream_V_V_dout;
wire    addWeight_stream_V_V_empty_n;
wire    out_stream_V_V_full_n;
wire   [31:0] out_stream_V_V_dout;
wire    out_stream_V_V_empty_n;
wire    ap_sync_done;
wire    ap_sync_ready;
wire   [0:0] start_for_bgr2gray_U0_din;
wire    start_for_bgr2gray_U0_full_n;
wire   [0:0] start_for_bgr2gray_U0_dout;
wire    start_for_bgr2gray_U0_empty_n;
wire   [0:0] start_for_Stream2Mem_Batch_U0_din;
wire    start_for_Stream2Mem_Batch_U0_full_n;
wire   [0:0] start_for_Stream2Mem_Batch_U0_dout;
wire    start_for_Stream2Mem_Batch_U0_empty_n;
wire   [0:0] start_for_gaussianBlur_U0_din;
wire    start_for_gaussianBlur_U0_full_n;
wire   [0:0] start_for_gaussianBlur_U0_dout;
wire    start_for_gaussianBlur_U0_empty_n;
wire   [0:0] start_for_sobel_x_U0_din;
wire    start_for_sobel_x_U0_full_n;
wire   [0:0] start_for_sobel_x_U0_dout;
wire    start_for_sobel_x_U0_empty_n;
wire   [0:0] start_for_sobel_y_U0_din;
wire    start_for_sobel_y_U0_full_n;
wire   [0:0] start_for_sobel_y_U0_dout;
wire    start_for_sobel_y_U0_empty_n;
wire   [0:0] start_for_addWeighted_U0_din;
wire    start_for_addWeighted_U0_full_n;
wire   [0:0] start_for_addWeighted_U0_dout;
wire    start_for_addWeighted_U0_empty_n;
wire    sobel_y_U0_start_full_n;
wire    sobel_y_U0_start_write;
wire   [0:0] start_for_gray2bgr_U0_din;
wire    start_for_gray2bgr_U0_full_n;
wire   [0:0] start_for_gray2bgr_U0_dout;
wire    start_for_gray2bgr_U0_empty_n;
wire    gray2bgr_U0_start_full_n;
wire    gray2bgr_U0_start_write;
wire    Stream2Mem_Batch_U0_start_full_n;
wire    Stream2Mem_Batch_U0_start_write;

image_filter_CONTROL_BUS_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_BUS_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_BUS_DATA_WIDTH ))
image_filter_CONTROL_BUS_s_axi_U(
    .AWVALID(s_axi_CONTROL_BUS_AWVALID),
    .AWREADY(s_axi_CONTROL_BUS_AWREADY),
    .AWADDR(s_axi_CONTROL_BUS_AWADDR),
    .WVALID(s_axi_CONTROL_BUS_WVALID),
    .WREADY(s_axi_CONTROL_BUS_WREADY),
    .WDATA(s_axi_CONTROL_BUS_WDATA),
    .WSTRB(s_axi_CONTROL_BUS_WSTRB),
    .ARVALID(s_axi_CONTROL_BUS_ARVALID),
    .ARREADY(s_axi_CONTROL_BUS_ARREADY),
    .ARADDR(s_axi_CONTROL_BUS_ARADDR),
    .RVALID(s_axi_CONTROL_BUS_RVALID),
    .RREADY(s_axi_CONTROL_BUS_RREADY),
    .RDATA(s_axi_CONTROL_BUS_RDATA),
    .RRESP(s_axi_CONTROL_BUS_RRESP),
    .BVALID(s_axi_CONTROL_BUS_BVALID),
    .BREADY(s_axi_CONTROL_BUS_BREADY),
    .BRESP(s_axi_CONTROL_BUS_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle),
    .in_V(in_V),
    .out_V(out_V),
    .rows(rows),
    .cols(cols)
);

image_filter_hostmem_1_m_axi #(
    .USER_DW( 32 ),
    .USER_AW( 32 ),
    .USER_MAXREQS( 5 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_HOSTMEM_1_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_HOSTMEM_1_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_HOSTMEM_1_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_HOSTMEM_1_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_HOSTMEM_1_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_HOSTMEM_1_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_HOSTMEM_1_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_HOSTMEM_1_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_HOSTMEM_1_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_HOSTMEM_1_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_HOSTMEM_1_CACHE_VALUE ))
image_filter_hostmem_1_m_axi_U(
    .AWVALID(m_axi_hostmem_1_AWVALID),
    .AWREADY(m_axi_hostmem_1_AWREADY),
    .AWADDR(m_axi_hostmem_1_AWADDR),
    .AWID(m_axi_hostmem_1_AWID),
    .AWLEN(m_axi_hostmem_1_AWLEN),
    .AWSIZE(m_axi_hostmem_1_AWSIZE),
    .AWBURST(m_axi_hostmem_1_AWBURST),
    .AWLOCK(m_axi_hostmem_1_AWLOCK),
    .AWCACHE(m_axi_hostmem_1_AWCACHE),
    .AWPROT(m_axi_hostmem_1_AWPROT),
    .AWQOS(m_axi_hostmem_1_AWQOS),
    .AWREGION(m_axi_hostmem_1_AWREGION),
    .AWUSER(m_axi_hostmem_1_AWUSER),
    .WVALID(m_axi_hostmem_1_WVALID),
    .WREADY(m_axi_hostmem_1_WREADY),
    .WDATA(m_axi_hostmem_1_WDATA),
    .WSTRB(m_axi_hostmem_1_WSTRB),
    .WLAST(m_axi_hostmem_1_WLAST),
    .WID(m_axi_hostmem_1_WID),
    .WUSER(m_axi_hostmem_1_WUSER),
    .ARVALID(m_axi_hostmem_1_ARVALID),
    .ARREADY(m_axi_hostmem_1_ARREADY),
    .ARADDR(m_axi_hostmem_1_ARADDR),
    .ARID(m_axi_hostmem_1_ARID),
    .ARLEN(m_axi_hostmem_1_ARLEN),
    .ARSIZE(m_axi_hostmem_1_ARSIZE),
    .ARBURST(m_axi_hostmem_1_ARBURST),
    .ARLOCK(m_axi_hostmem_1_ARLOCK),
    .ARCACHE(m_axi_hostmem_1_ARCACHE),
    .ARPROT(m_axi_hostmem_1_ARPROT),
    .ARQOS(m_axi_hostmem_1_ARQOS),
    .ARREGION(m_axi_hostmem_1_ARREGION),
    .ARUSER(m_axi_hostmem_1_ARUSER),
    .RVALID(m_axi_hostmem_1_RVALID),
    .RREADY(m_axi_hostmem_1_RREADY),
    .RDATA(m_axi_hostmem_1_RDATA),
    .RLAST(m_axi_hostmem_1_RLAST),
    .RID(m_axi_hostmem_1_RID),
    .RUSER(m_axi_hostmem_1_RUSER),
    .RRESP(m_axi_hostmem_1_RRESP),
    .BVALID(m_axi_hostmem_1_BVALID),
    .BREADY(m_axi_hostmem_1_BREADY),
    .BRESP(m_axi_hostmem_1_BRESP),
    .BID(m_axi_hostmem_1_BID),
    .BUSER(m_axi_hostmem_1_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(Mem2Stream_Batch9_U0_m_axi_in_V_ARVALID),
    .I_ARREADY(hostmem_1_ARREADY),
    .I_ARADDR(Mem2Stream_Batch9_U0_m_axi_in_V_ARADDR),
    .I_ARID(Mem2Stream_Batch9_U0_m_axi_in_V_ARID),
    .I_ARLEN(Mem2Stream_Batch9_U0_m_axi_in_V_ARLEN),
    .I_ARSIZE(Mem2Stream_Batch9_U0_m_axi_in_V_ARSIZE),
    .I_ARLOCK(Mem2Stream_Batch9_U0_m_axi_in_V_ARLOCK),
    .I_ARCACHE(Mem2Stream_Batch9_U0_m_axi_in_V_ARCACHE),
    .I_ARQOS(Mem2Stream_Batch9_U0_m_axi_in_V_ARQOS),
    .I_ARPROT(Mem2Stream_Batch9_U0_m_axi_in_V_ARPROT),
    .I_ARUSER(Mem2Stream_Batch9_U0_m_axi_in_V_ARUSER),
    .I_ARBURST(Mem2Stream_Batch9_U0_m_axi_in_V_ARBURST),
    .I_ARREGION(Mem2Stream_Batch9_U0_m_axi_in_V_ARREGION),
    .I_RVALID(hostmem_1_RVALID),
    .I_RREADY(Mem2Stream_Batch9_U0_m_axi_in_V_RREADY),
    .I_RDATA(hostmem_1_RDATA),
    .I_RID(hostmem_1_RID),
    .I_RUSER(hostmem_1_RUSER),
    .I_RRESP(hostmem_1_RRESP),
    .I_RLAST(hostmem_1_RLAST),
    .I_AWVALID(1'b0),
    .I_AWREADY(hostmem_1_AWREADY),
    .I_AWADDR(32'd0),
    .I_AWID(1'd0),
    .I_AWLEN(32'd0),
    .I_AWSIZE(3'd0),
    .I_AWLOCK(2'd0),
    .I_AWCACHE(4'd0),
    .I_AWQOS(4'd0),
    .I_AWPROT(3'd0),
    .I_AWUSER(1'd0),
    .I_AWBURST(2'd0),
    .I_AWREGION(4'd0),
    .I_WVALID(1'b0),
    .I_WREADY(hostmem_1_WREADY),
    .I_WDATA(32'd0),
    .I_WID(1'd0),
    .I_WUSER(1'd0),
    .I_WLAST(1'b0),
    .I_WSTRB(4'd0),
    .I_BVALID(hostmem_1_BVALID),
    .I_BREADY(1'b0),
    .I_BRESP(hostmem_1_BRESP),
    .I_BID(hostmem_1_BID),
    .I_BUSER(hostmem_1_BUSER)
);

image_filter_hostmem_2_m_axi #(
    .USER_DW( 32 ),
    .USER_AW( 32 ),
    .USER_MAXREQS( 5 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_HOSTMEM_2_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_HOSTMEM_2_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_HOSTMEM_2_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_HOSTMEM_2_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_HOSTMEM_2_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_HOSTMEM_2_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_HOSTMEM_2_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_HOSTMEM_2_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_HOSTMEM_2_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_HOSTMEM_2_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_HOSTMEM_2_CACHE_VALUE ))
image_filter_hostmem_2_m_axi_U(
    .AWVALID(m_axi_hostmem_2_AWVALID),
    .AWREADY(m_axi_hostmem_2_AWREADY),
    .AWADDR(m_axi_hostmem_2_AWADDR),
    .AWID(m_axi_hostmem_2_AWID),
    .AWLEN(m_axi_hostmem_2_AWLEN),
    .AWSIZE(m_axi_hostmem_2_AWSIZE),
    .AWBURST(m_axi_hostmem_2_AWBURST),
    .AWLOCK(m_axi_hostmem_2_AWLOCK),
    .AWCACHE(m_axi_hostmem_2_AWCACHE),
    .AWPROT(m_axi_hostmem_2_AWPROT),
    .AWQOS(m_axi_hostmem_2_AWQOS),
    .AWREGION(m_axi_hostmem_2_AWREGION),
    .AWUSER(m_axi_hostmem_2_AWUSER),
    .WVALID(m_axi_hostmem_2_WVALID),
    .WREADY(m_axi_hostmem_2_WREADY),
    .WDATA(m_axi_hostmem_2_WDATA),
    .WSTRB(m_axi_hostmem_2_WSTRB),
    .WLAST(m_axi_hostmem_2_WLAST),
    .WID(m_axi_hostmem_2_WID),
    .WUSER(m_axi_hostmem_2_WUSER),
    .ARVALID(m_axi_hostmem_2_ARVALID),
    .ARREADY(m_axi_hostmem_2_ARREADY),
    .ARADDR(m_axi_hostmem_2_ARADDR),
    .ARID(m_axi_hostmem_2_ARID),
    .ARLEN(m_axi_hostmem_2_ARLEN),
    .ARSIZE(m_axi_hostmem_2_ARSIZE),
    .ARBURST(m_axi_hostmem_2_ARBURST),
    .ARLOCK(m_axi_hostmem_2_ARLOCK),
    .ARCACHE(m_axi_hostmem_2_ARCACHE),
    .ARPROT(m_axi_hostmem_2_ARPROT),
    .ARQOS(m_axi_hostmem_2_ARQOS),
    .ARREGION(m_axi_hostmem_2_ARREGION),
    .ARUSER(m_axi_hostmem_2_ARUSER),
    .RVALID(m_axi_hostmem_2_RVALID),
    .RREADY(m_axi_hostmem_2_RREADY),
    .RDATA(m_axi_hostmem_2_RDATA),
    .RLAST(m_axi_hostmem_2_RLAST),
    .RID(m_axi_hostmem_2_RID),
    .RUSER(m_axi_hostmem_2_RUSER),
    .RRESP(m_axi_hostmem_2_RRESP),
    .BVALID(m_axi_hostmem_2_BVALID),
    .BREADY(m_axi_hostmem_2_BREADY),
    .BRESP(m_axi_hostmem_2_BRESP),
    .BID(m_axi_hostmem_2_BID),
    .BUSER(m_axi_hostmem_2_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(1'b0),
    .I_ARREADY(hostmem_2_ARREADY),
    .I_ARADDR(32'd0),
    .I_ARID(1'd0),
    .I_ARLEN(32'd0),
    .I_ARSIZE(3'd0),
    .I_ARLOCK(2'd0),
    .I_ARCACHE(4'd0),
    .I_ARQOS(4'd0),
    .I_ARPROT(3'd0),
    .I_ARUSER(1'd0),
    .I_ARBURST(2'd0),
    .I_ARREGION(4'd0),
    .I_RVALID(hostmem_2_RVALID),
    .I_RREADY(1'b0),
    .I_RDATA(hostmem_2_RDATA),
    .I_RID(hostmem_2_RID),
    .I_RUSER(hostmem_2_RUSER),
    .I_RRESP(hostmem_2_RRESP),
    .I_RLAST(hostmem_2_RLAST),
    .I_AWVALID(Stream2Mem_Batch_U0_m_axi_out_V_AWVALID),
    .I_AWREADY(hostmem_2_AWREADY),
    .I_AWADDR(Stream2Mem_Batch_U0_m_axi_out_V_AWADDR),
    .I_AWID(Stream2Mem_Batch_U0_m_axi_out_V_AWID),
    .I_AWLEN(Stream2Mem_Batch_U0_m_axi_out_V_AWLEN),
    .I_AWSIZE(Stream2Mem_Batch_U0_m_axi_out_V_AWSIZE),
    .I_AWLOCK(Stream2Mem_Batch_U0_m_axi_out_V_AWLOCK),
    .I_AWCACHE(Stream2Mem_Batch_U0_m_axi_out_V_AWCACHE),
    .I_AWQOS(Stream2Mem_Batch_U0_m_axi_out_V_AWQOS),
    .I_AWPROT(Stream2Mem_Batch_U0_m_axi_out_V_AWPROT),
    .I_AWUSER(Stream2Mem_Batch_U0_m_axi_out_V_AWUSER),
    .I_AWBURST(Stream2Mem_Batch_U0_m_axi_out_V_AWBURST),
    .I_AWREGION(Stream2Mem_Batch_U0_m_axi_out_V_AWREGION),
    .I_WVALID(Stream2Mem_Batch_U0_m_axi_out_V_WVALID),
    .I_WREADY(hostmem_2_WREADY),
    .I_WDATA(Stream2Mem_Batch_U0_m_axi_out_V_WDATA),
    .I_WID(Stream2Mem_Batch_U0_m_axi_out_V_WID),
    .I_WUSER(Stream2Mem_Batch_U0_m_axi_out_V_WUSER),
    .I_WLAST(Stream2Mem_Batch_U0_m_axi_out_V_WLAST),
    .I_WSTRB(Stream2Mem_Batch_U0_m_axi_out_V_WSTRB),
    .I_BVALID(hostmem_2_BVALID),
    .I_BREADY(Stream2Mem_Batch_U0_m_axi_out_V_BREADY),
    .I_BRESP(hostmem_2_BRESP),
    .I_BID(hostmem_2_BID),
    .I_BUSER(hostmem_2_BUSER)
);

Mem2Stream_Batch9 Mem2Stream_Batch9_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(Mem2Stream_Batch9_U0_ap_start),
    .start_full_n(Mem2Stream_Batch9_U0_start_full_n),
    .ap_done(Mem2Stream_Batch9_U0_ap_done),
    .ap_continue(Mem2Stream_Batch9_U0_ap_continue),
    .ap_idle(Mem2Stream_Batch9_U0_ap_idle),
    .ap_ready(Mem2Stream_Batch9_U0_ap_ready),
    .start_out(Mem2Stream_Batch9_U0_start_out),
    .start_write(Mem2Stream_Batch9_U0_start_write),
    .m_axi_in_V_AWVALID(Mem2Stream_Batch9_U0_m_axi_in_V_AWVALID),
    .m_axi_in_V_AWREADY(1'b0),
    .m_axi_in_V_AWADDR(Mem2Stream_Batch9_U0_m_axi_in_V_AWADDR),
    .m_axi_in_V_AWID(Mem2Stream_Batch9_U0_m_axi_in_V_AWID),
    .m_axi_in_V_AWLEN(Mem2Stream_Batch9_U0_m_axi_in_V_AWLEN),
    .m_axi_in_V_AWSIZE(Mem2Stream_Batch9_U0_m_axi_in_V_AWSIZE),
    .m_axi_in_V_AWBURST(Mem2Stream_Batch9_U0_m_axi_in_V_AWBURST),
    .m_axi_in_V_AWLOCK(Mem2Stream_Batch9_U0_m_axi_in_V_AWLOCK),
    .m_axi_in_V_AWCACHE(Mem2Stream_Batch9_U0_m_axi_in_V_AWCACHE),
    .m_axi_in_V_AWPROT(Mem2Stream_Batch9_U0_m_axi_in_V_AWPROT),
    .m_axi_in_V_AWQOS(Mem2Stream_Batch9_U0_m_axi_in_V_AWQOS),
    .m_axi_in_V_AWREGION(Mem2Stream_Batch9_U0_m_axi_in_V_AWREGION),
    .m_axi_in_V_AWUSER(Mem2Stream_Batch9_U0_m_axi_in_V_AWUSER),
    .m_axi_in_V_WVALID(Mem2Stream_Batch9_U0_m_axi_in_V_WVALID),
    .m_axi_in_V_WREADY(1'b0),
    .m_axi_in_V_WDATA(Mem2Stream_Batch9_U0_m_axi_in_V_WDATA),
    .m_axi_in_V_WSTRB(Mem2Stream_Batch9_U0_m_axi_in_V_WSTRB),
    .m_axi_in_V_WLAST(Mem2Stream_Batch9_U0_m_axi_in_V_WLAST),
    .m_axi_in_V_WID(Mem2Stream_Batch9_U0_m_axi_in_V_WID),
    .m_axi_in_V_WUSER(Mem2Stream_Batch9_U0_m_axi_in_V_WUSER),
    .m_axi_in_V_ARVALID(Mem2Stream_Batch9_U0_m_axi_in_V_ARVALID),
    .m_axi_in_V_ARREADY(hostmem_1_ARREADY),
    .m_axi_in_V_ARADDR(Mem2Stream_Batch9_U0_m_axi_in_V_ARADDR),
    .m_axi_in_V_ARID(Mem2Stream_Batch9_U0_m_axi_in_V_ARID),
    .m_axi_in_V_ARLEN(Mem2Stream_Batch9_U0_m_axi_in_V_ARLEN),
    .m_axi_in_V_ARSIZE(Mem2Stream_Batch9_U0_m_axi_in_V_ARSIZE),
    .m_axi_in_V_ARBURST(Mem2Stream_Batch9_U0_m_axi_in_V_ARBURST),
    .m_axi_in_V_ARLOCK(Mem2Stream_Batch9_U0_m_axi_in_V_ARLOCK),
    .m_axi_in_V_ARCACHE(Mem2Stream_Batch9_U0_m_axi_in_V_ARCACHE),
    .m_axi_in_V_ARPROT(Mem2Stream_Batch9_U0_m_axi_in_V_ARPROT),
    .m_axi_in_V_ARQOS(Mem2Stream_Batch9_U0_m_axi_in_V_ARQOS),
    .m_axi_in_V_ARREGION(Mem2Stream_Batch9_U0_m_axi_in_V_ARREGION),
    .m_axi_in_V_ARUSER(Mem2Stream_Batch9_U0_m_axi_in_V_ARUSER),
    .m_axi_in_V_RVALID(hostmem_1_RVALID),
    .m_axi_in_V_RREADY(Mem2Stream_Batch9_U0_m_axi_in_V_RREADY),
    .m_axi_in_V_RDATA(hostmem_1_RDATA),
    .m_axi_in_V_RLAST(hostmem_1_RLAST),
    .m_axi_in_V_RID(hostmem_1_RID),
    .m_axi_in_V_RUSER(hostmem_1_RUSER),
    .m_axi_in_V_RRESP(hostmem_1_RRESP),
    .m_axi_in_V_BVALID(1'b0),
    .m_axi_in_V_BREADY(Mem2Stream_Batch9_U0_m_axi_in_V_BREADY),
    .m_axi_in_V_BRESP(2'd0),
    .m_axi_in_V_BID(1'd0),
    .m_axi_in_V_BUSER(1'd0),
    .in_V_offset(in_V),
    .out_V_V_din(Mem2Stream_Batch9_U0_out_V_V_din),
    .out_V_V_full_n(in_stream_V_V_full_n),
    .out_V_V_write(Mem2Stream_Batch9_U0_out_V_V_write),
    .out_V(out_V),
    .out_V_out_din(Mem2Stream_Batch9_U0_out_V_out_din),
    .out_V_out_full_n(out_V_c_full_n),
    .out_V_out_write(Mem2Stream_Batch9_U0_out_V_out_write)
);

bgr2gray bgr2gray_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(bgr2gray_U0_ap_start),
    .start_full_n(start_for_gaussianBlur_U0_full_n),
    .ap_done(bgr2gray_U0_ap_done),
    .ap_continue(bgr2gray_U0_ap_continue),
    .ap_idle(bgr2gray_U0_ap_idle),
    .ap_ready(bgr2gray_U0_ap_ready),
    .start_out(bgr2gray_U0_start_out),
    .start_write(bgr2gray_U0_start_write),
    .src_V_V_dout(in_stream_V_V_dout),
    .src_V_V_empty_n(in_stream_V_V_empty_n),
    .src_V_V_read(bgr2gray_U0_src_V_V_read),
    .dst_V_V_din(bgr2gray_U0_dst_V_V_din),
    .dst_V_V_full_n(gray_stream_V_V_full_n),
    .dst_V_V_write(bgr2gray_U0_dst_V_V_write)
);

gaussianBlur gaussianBlur_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(gaussianBlur_U0_ap_start),
    .start_full_n(gaussianBlur_U0_start_full_n),
    .ap_done(gaussianBlur_U0_ap_done),
    .ap_continue(gaussianBlur_U0_ap_continue),
    .ap_idle(gaussianBlur_U0_ap_idle),
    .ap_ready(gaussianBlur_U0_ap_ready),
    .start_out(gaussianBlur_U0_start_out),
    .start_write(gaussianBlur_U0_start_write),
    .src_V_V_dout(gray_stream_V_V_dout),
    .src_V_V_empty_n(gray_stream_V_V_empty_n),
    .src_V_V_read(gaussianBlur_U0_src_V_V_read),
    .dst_x_V_V_din(gaussianBlur_U0_dst_x_V_V_din),
    .dst_x_V_V_full_n(gaussian_stream_x_V_s_full_n),
    .dst_x_V_V_write(gaussianBlur_U0_dst_x_V_V_write),
    .dst_y_V_V_din(gaussianBlur_U0_dst_y_V_V_din),
    .dst_y_V_V_full_n(gaussian_stream_y_V_s_full_n),
    .dst_y_V_V_write(gaussianBlur_U0_dst_y_V_V_write)
);

sobel_x sobel_x_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(sobel_x_U0_ap_start),
    .start_full_n(start_for_addWeighted_U0_full_n),
    .ap_done(sobel_x_U0_ap_done),
    .ap_continue(sobel_x_U0_ap_continue),
    .ap_idle(sobel_x_U0_ap_idle),
    .ap_ready(sobel_x_U0_ap_ready),
    .start_out(sobel_x_U0_start_out),
    .start_write(sobel_x_U0_start_write),
    .src_V_V_dout(gaussian_stream_x_V_s_dout),
    .src_V_V_empty_n(gaussian_stream_x_V_s_empty_n),
    .src_V_V_read(sobel_x_U0_src_V_V_read),
    .dst_V_V_din(sobel_x_U0_dst_V_V_din),
    .dst_V_V_full_n(sobel_stream_x_V_V_full_n),
    .dst_V_V_write(sobel_x_U0_dst_V_V_write)
);

sobel_y sobel_y_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(sobel_y_U0_ap_start),
    .ap_done(sobel_y_U0_ap_done),
    .ap_continue(sobel_y_U0_ap_continue),
    .ap_idle(sobel_y_U0_ap_idle),
    .ap_ready(sobel_y_U0_ap_ready),
    .src_V_V_dout(gaussian_stream_y_V_s_dout),
    .src_V_V_empty_n(gaussian_stream_y_V_s_empty_n),
    .src_V_V_read(sobel_y_U0_src_V_V_read),
    .dst_V_V_din(sobel_y_U0_dst_V_V_din),
    .dst_V_V_full_n(sobel_stream_y_V_V_full_n),
    .dst_V_V_write(sobel_y_U0_dst_V_V_write)
);

addWeighted addWeighted_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(addWeighted_U0_ap_start),
    .start_full_n(start_for_gray2bgr_U0_full_n),
    .ap_done(addWeighted_U0_ap_done),
    .ap_continue(addWeighted_U0_ap_continue),
    .ap_idle(addWeighted_U0_ap_idle),
    .ap_ready(addWeighted_U0_ap_ready),
    .start_out(addWeighted_U0_start_out),
    .start_write(addWeighted_U0_start_write),
    .src_x_V_V_dout(sobel_stream_x_V_V_dout),
    .src_x_V_V_empty_n(sobel_stream_x_V_V_empty_n),
    .src_x_V_V_read(addWeighted_U0_src_x_V_V_read),
    .src_y_V_V_dout(sobel_stream_y_V_V_dout),
    .src_y_V_V_empty_n(sobel_stream_y_V_V_empty_n),
    .src_y_V_V_read(addWeighted_U0_src_y_V_V_read),
    .dst_V_V_din(addWeighted_U0_dst_V_V_din),
    .dst_V_V_full_n(addWeight_stream_V_V_full_n),
    .dst_V_V_write(addWeighted_U0_dst_V_V_write)
);

gray2bgr gray2bgr_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(gray2bgr_U0_ap_start),
    .ap_done(gray2bgr_U0_ap_done),
    .ap_continue(gray2bgr_U0_ap_continue),
    .ap_idle(gray2bgr_U0_ap_idle),
    .ap_ready(gray2bgr_U0_ap_ready),
    .src_V_V_dout(addWeight_stream_V_V_dout),
    .src_V_V_empty_n(addWeight_stream_V_V_empty_n),
    .src_V_V_read(gray2bgr_U0_src_V_V_read),
    .dst_V_V_din(gray2bgr_U0_dst_V_V_din),
    .dst_V_V_full_n(out_stream_V_V_full_n),
    .dst_V_V_write(gray2bgr_U0_dst_V_V_write)
);

Stream2Mem_Batch Stream2Mem_Batch_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(Stream2Mem_Batch_U0_ap_start),
    .ap_done(Stream2Mem_Batch_U0_ap_done),
    .ap_continue(Stream2Mem_Batch_U0_ap_continue),
    .ap_idle(Stream2Mem_Batch_U0_ap_idle),
    .ap_ready(Stream2Mem_Batch_U0_ap_ready),
    .in_V_V_dout(out_stream_V_V_dout),
    .in_V_V_empty_n(out_stream_V_V_empty_n),
    .in_V_V_read(Stream2Mem_Batch_U0_in_V_V_read),
    .m_axi_out_V_AWVALID(Stream2Mem_Batch_U0_m_axi_out_V_AWVALID),
    .m_axi_out_V_AWREADY(hostmem_2_AWREADY),
    .m_axi_out_V_AWADDR(Stream2Mem_Batch_U0_m_axi_out_V_AWADDR),
    .m_axi_out_V_AWID(Stream2Mem_Batch_U0_m_axi_out_V_AWID),
    .m_axi_out_V_AWLEN(Stream2Mem_Batch_U0_m_axi_out_V_AWLEN),
    .m_axi_out_V_AWSIZE(Stream2Mem_Batch_U0_m_axi_out_V_AWSIZE),
    .m_axi_out_V_AWBURST(Stream2Mem_Batch_U0_m_axi_out_V_AWBURST),
    .m_axi_out_V_AWLOCK(Stream2Mem_Batch_U0_m_axi_out_V_AWLOCK),
    .m_axi_out_V_AWCACHE(Stream2Mem_Batch_U0_m_axi_out_V_AWCACHE),
    .m_axi_out_V_AWPROT(Stream2Mem_Batch_U0_m_axi_out_V_AWPROT),
    .m_axi_out_V_AWQOS(Stream2Mem_Batch_U0_m_axi_out_V_AWQOS),
    .m_axi_out_V_AWREGION(Stream2Mem_Batch_U0_m_axi_out_V_AWREGION),
    .m_axi_out_V_AWUSER(Stream2Mem_Batch_U0_m_axi_out_V_AWUSER),
    .m_axi_out_V_WVALID(Stream2Mem_Batch_U0_m_axi_out_V_WVALID),
    .m_axi_out_V_WREADY(hostmem_2_WREADY),
    .m_axi_out_V_WDATA(Stream2Mem_Batch_U0_m_axi_out_V_WDATA),
    .m_axi_out_V_WSTRB(Stream2Mem_Batch_U0_m_axi_out_V_WSTRB),
    .m_axi_out_V_WLAST(Stream2Mem_Batch_U0_m_axi_out_V_WLAST),
    .m_axi_out_V_WID(Stream2Mem_Batch_U0_m_axi_out_V_WID),
    .m_axi_out_V_WUSER(Stream2Mem_Batch_U0_m_axi_out_V_WUSER),
    .m_axi_out_V_ARVALID(Stream2Mem_Batch_U0_m_axi_out_V_ARVALID),
    .m_axi_out_V_ARREADY(1'b0),
    .m_axi_out_V_ARADDR(Stream2Mem_Batch_U0_m_axi_out_V_ARADDR),
    .m_axi_out_V_ARID(Stream2Mem_Batch_U0_m_axi_out_V_ARID),
    .m_axi_out_V_ARLEN(Stream2Mem_Batch_U0_m_axi_out_V_ARLEN),
    .m_axi_out_V_ARSIZE(Stream2Mem_Batch_U0_m_axi_out_V_ARSIZE),
    .m_axi_out_V_ARBURST(Stream2Mem_Batch_U0_m_axi_out_V_ARBURST),
    .m_axi_out_V_ARLOCK(Stream2Mem_Batch_U0_m_axi_out_V_ARLOCK),
    .m_axi_out_V_ARCACHE(Stream2Mem_Batch_U0_m_axi_out_V_ARCACHE),
    .m_axi_out_V_ARPROT(Stream2Mem_Batch_U0_m_axi_out_V_ARPROT),
    .m_axi_out_V_ARQOS(Stream2Mem_Batch_U0_m_axi_out_V_ARQOS),
    .m_axi_out_V_ARREGION(Stream2Mem_Batch_U0_m_axi_out_V_ARREGION),
    .m_axi_out_V_ARUSER(Stream2Mem_Batch_U0_m_axi_out_V_ARUSER),
    .m_axi_out_V_RVALID(1'b0),
    .m_axi_out_V_RREADY(Stream2Mem_Batch_U0_m_axi_out_V_RREADY),
    .m_axi_out_V_RDATA(32'd0),
    .m_axi_out_V_RLAST(1'b0),
    .m_axi_out_V_RID(1'd0),
    .m_axi_out_V_RUSER(1'd0),
    .m_axi_out_V_RRESP(2'd0),
    .m_axi_out_V_BVALID(hostmem_2_BVALID),
    .m_axi_out_V_BREADY(Stream2Mem_Batch_U0_m_axi_out_V_BREADY),
    .m_axi_out_V_BRESP(hostmem_2_BRESP),
    .m_axi_out_V_BID(hostmem_2_BID),
    .m_axi_out_V_BUSER(hostmem_2_BUSER),
    .out_V_offset_dout(out_V_c_dout),
    .out_V_offset_empty_n(out_V_c_empty_n),
    .out_V_offset_read(Stream2Mem_Batch_U0_out_V_offset_read)
);

fifo_w32_d128_A in_stream_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Mem2Stream_Batch9_U0_out_V_V_din),
    .if_full_n(in_stream_V_V_full_n),
    .if_write(Mem2Stream_Batch9_U0_out_V_V_write),
    .if_dout(in_stream_V_V_dout),
    .if_empty_n(in_stream_V_V_empty_n),
    .if_read(bgr2gray_U0_src_V_V_read)
);

fifo_w32_d6_A out_V_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Mem2Stream_Batch9_U0_out_V_out_din),
    .if_full_n(out_V_c_full_n),
    .if_write(Mem2Stream_Batch9_U0_out_V_out_write),
    .if_dout(out_V_c_dout),
    .if_empty_n(out_V_c_empty_n),
    .if_read(Stream2Mem_Batch_U0_out_V_offset_read)
);

fifo_w8_d128_A gray_stream_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(bgr2gray_U0_dst_V_V_din),
    .if_full_n(gray_stream_V_V_full_n),
    .if_write(bgr2gray_U0_dst_V_V_write),
    .if_dout(gray_stream_V_V_dout),
    .if_empty_n(gray_stream_V_V_empty_n),
    .if_read(gaussianBlur_U0_src_V_V_read)
);

fifo_w8_d128_A gaussian_stream_x_V_s_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(gaussianBlur_U0_dst_x_V_V_din),
    .if_full_n(gaussian_stream_x_V_s_full_n),
    .if_write(gaussianBlur_U0_dst_x_V_V_write),
    .if_dout(gaussian_stream_x_V_s_dout),
    .if_empty_n(gaussian_stream_x_V_s_empty_n),
    .if_read(sobel_x_U0_src_V_V_read)
);

fifo_w8_d128_A gaussian_stream_y_V_s_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(gaussianBlur_U0_dst_y_V_V_din),
    .if_full_n(gaussian_stream_y_V_s_full_n),
    .if_write(gaussianBlur_U0_dst_y_V_V_write),
    .if_dout(gaussian_stream_y_V_s_dout),
    .if_empty_n(gaussian_stream_y_V_s_empty_n),
    .if_read(sobel_y_U0_src_V_V_read)
);

fifo_w8_d128_A sobel_stream_x_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(sobel_x_U0_dst_V_V_din),
    .if_full_n(sobel_stream_x_V_V_full_n),
    .if_write(sobel_x_U0_dst_V_V_write),
    .if_dout(sobel_stream_x_V_V_dout),
    .if_empty_n(sobel_stream_x_V_V_empty_n),
    .if_read(addWeighted_U0_src_x_V_V_read)
);

fifo_w8_d128_A sobel_stream_y_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(sobel_y_U0_dst_V_V_din),
    .if_full_n(sobel_stream_y_V_V_full_n),
    .if_write(sobel_y_U0_dst_V_V_write),
    .if_dout(sobel_stream_y_V_V_dout),
    .if_empty_n(sobel_stream_y_V_V_empty_n),
    .if_read(addWeighted_U0_src_y_V_V_read)
);

fifo_w8_d128_A addWeight_stream_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(addWeighted_U0_dst_V_V_din),
    .if_full_n(addWeight_stream_V_V_full_n),
    .if_write(addWeighted_U0_dst_V_V_write),
    .if_dout(addWeight_stream_V_V_dout),
    .if_empty_n(addWeight_stream_V_V_empty_n),
    .if_read(gray2bgr_U0_src_V_V_read)
);

fifo_w32_d128_A out_stream_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(gray2bgr_U0_dst_V_V_din),
    .if_full_n(out_stream_V_V_full_n),
    .if_write(gray2bgr_U0_dst_V_V_write),
    .if_dout(out_stream_V_V_dout),
    .if_empty_n(out_stream_V_V_empty_n),
    .if_read(Stream2Mem_Batch_U0_in_V_V_read)
);

start_for_bgr2grapcA start_for_bgr2grapcA_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_bgr2gray_U0_din),
    .if_full_n(start_for_bgr2gray_U0_full_n),
    .if_write(Mem2Stream_Batch9_U0_start_write),
    .if_dout(start_for_bgr2gray_U0_dout),
    .if_empty_n(start_for_bgr2gray_U0_empty_n),
    .if_read(bgr2gray_U0_ap_ready)
);

start_for_Stream2qcK start_for_Stream2qcK_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_Stream2Mem_Batch_U0_din),
    .if_full_n(start_for_Stream2Mem_Batch_U0_full_n),
    .if_write(Mem2Stream_Batch9_U0_start_write),
    .if_dout(start_for_Stream2Mem_Batch_U0_dout),
    .if_empty_n(start_for_Stream2Mem_Batch_U0_empty_n),
    .if_read(Stream2Mem_Batch_U0_ap_ready)
);

start_for_gaussiarcU start_for_gaussiarcU_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_gaussianBlur_U0_din),
    .if_full_n(start_for_gaussianBlur_U0_full_n),
    .if_write(bgr2gray_U0_start_write),
    .if_dout(start_for_gaussianBlur_U0_dout),
    .if_empty_n(start_for_gaussianBlur_U0_empty_n),
    .if_read(gaussianBlur_U0_ap_ready)
);

start_for_sobel_xsc4 start_for_sobel_xsc4_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_sobel_x_U0_din),
    .if_full_n(start_for_sobel_x_U0_full_n),
    .if_write(gaussianBlur_U0_start_write),
    .if_dout(start_for_sobel_x_U0_dout),
    .if_empty_n(start_for_sobel_x_U0_empty_n),
    .if_read(sobel_x_U0_ap_ready)
);

start_for_sobel_ytde start_for_sobel_ytde_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_sobel_y_U0_din),
    .if_full_n(start_for_sobel_y_U0_full_n),
    .if_write(gaussianBlur_U0_start_write),
    .if_dout(start_for_sobel_y_U0_dout),
    .if_empty_n(start_for_sobel_y_U0_empty_n),
    .if_read(sobel_y_U0_ap_ready)
);

start_for_addWeigudo start_for_addWeigudo_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_addWeighted_U0_din),
    .if_full_n(start_for_addWeighted_U0_full_n),
    .if_write(sobel_x_U0_start_write),
    .if_dout(start_for_addWeighted_U0_dout),
    .if_empty_n(start_for_addWeighted_U0_empty_n),
    .if_read(addWeighted_U0_ap_ready)
);

start_for_gray2bgvdy start_for_gray2bgvdy_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_gray2bgr_U0_din),
    .if_full_n(start_for_gray2bgr_U0_full_n),
    .if_write(addWeighted_U0_start_write),
    .if_dout(start_for_gray2bgr_U0_dout),
    .if_empty_n(start_for_gray2bgr_U0_empty_n),
    .if_read(gray2bgr_U0_ap_ready)
);

assign Mem2Stream_Batch9_U0_ap_continue = 1'b1;

assign Mem2Stream_Batch9_U0_ap_start = ap_start;

assign Mem2Stream_Batch9_U0_start_full_n = (start_for_bgr2gray_U0_full_n & start_for_Stream2Mem_Batch_U0_full_n);

assign Stream2Mem_Batch_U0_ap_continue = 1'b1;

assign Stream2Mem_Batch_U0_ap_start = start_for_Stream2Mem_Batch_U0_empty_n;

assign Stream2Mem_Batch_U0_start_full_n = 1'b1;

assign Stream2Mem_Batch_U0_start_write = 1'b0;

assign addWeighted_U0_ap_continue = 1'b1;

assign addWeighted_U0_ap_start = start_for_addWeighted_U0_empty_n;

assign ap_done = Stream2Mem_Batch_U0_ap_done;

assign ap_idle = (sobel_y_U0_ap_idle & sobel_x_U0_ap_idle & gray2bgr_U0_ap_idle & gaussianBlur_U0_ap_idle & bgr2gray_U0_ap_idle & addWeighted_U0_ap_idle & Stream2Mem_Batch_U0_ap_idle & Mem2Stream_Batch9_U0_ap_idle);

assign ap_ready = Mem2Stream_Batch9_U0_ap_ready;

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign ap_sync_continue = 1'b1;

assign ap_sync_done = Stream2Mem_Batch_U0_ap_done;

assign ap_sync_ready = Mem2Stream_Batch9_U0_ap_ready;

assign bgr2gray_U0_ap_continue = 1'b1;

assign bgr2gray_U0_ap_start = start_for_bgr2gray_U0_empty_n;

assign gaussianBlur_U0_ap_continue = 1'b1;

assign gaussianBlur_U0_ap_start = start_for_gaussianBlur_U0_empty_n;

assign gaussianBlur_U0_start_full_n = (start_for_sobel_y_U0_full_n & start_for_sobel_x_U0_full_n);

assign gray2bgr_U0_ap_continue = 1'b1;

assign gray2bgr_U0_ap_start = start_for_gray2bgr_U0_empty_n;

assign gray2bgr_U0_start_full_n = 1'b1;

assign gray2bgr_U0_start_write = 1'b0;

assign sobel_x_U0_ap_continue = 1'b1;

assign sobel_x_U0_ap_start = start_for_sobel_x_U0_empty_n;

assign sobel_y_U0_ap_continue = 1'b1;

assign sobel_y_U0_ap_start = start_for_sobel_y_U0_empty_n;

assign sobel_y_U0_start_full_n = 1'b1;

assign sobel_y_U0_start_write = 1'b0;

assign start_for_Stream2Mem_Batch_U0_din = 1'b1;

assign start_for_addWeighted_U0_din = 1'b1;

assign start_for_bgr2gray_U0_din = 1'b1;

assign start_for_gaussianBlur_U0_din = 1'b1;

assign start_for_gray2bgr_U0_din = 1'b1;

assign start_for_sobel_x_U0_din = 1'b1;

assign start_for_sobel_y_U0_din = 1'b1;

endmodule //image_filter
